# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-16 22:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('galaxy_dataset', models.URLField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'assemblies',
            },
        ),
        migrations.CreateModel(
            name='Bacteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=64)),
                ('species', models.CharField(blank=True, max_length=64)),
                ('strain', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name_plural': 'bacteria',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('collection', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalSampleCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalSampleRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_collection', models.BooleanField(default=False, help_text="Whether or not this is a 'true' collection of multiple phages, or simply the default collection instance auto-created for an environmental sample")),
                ('es', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.EnvironmentalSample')),
                ('esc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.EnvironmentalSampleCollection')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=32)),
                ('full_name', models.TextField()),
                ('methods', models.TextField()),
                ('category', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentalResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.TextField()),
                ('date', models.DateTimeField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.Experiment')),
                ('run_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Lysate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('oldid', models.CharField(blank=True, max_length=64)),
                ('isolation', models.DateTimeField(blank=True, null=True)),
                ('env_sample_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.EnvironmentalSampleCollection')),
                ('host', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Bacteria')),
            ],
        ),
        migrations.CreateModel(
            name='Phage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_name', models.CharField(max_length=64)),
                ('historical_names', models.TextField(blank=True, null=True)),
                ('host', models.ManyToManyField(blank=True, to='lims.Bacteria')),
                ('lysate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Lysate')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='PhageDNAPrep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('morphology', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Podophage'), (2, 'Myophage'), (3, 'Siphophage')])),
                ('experiments', models.ManyToManyField(blank=True, to='lims.ExperimentalResult')),
            ],
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SequencingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('galaxy_history', models.URLField()),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('bioanalyzer_qc', models.TextField()),
                ('run_prep_spreadsheet', models.URLField()),
                ('methods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.Experiment')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='SequencingRunPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pool', models.CharField(max_length=16)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.SequencingRun')),
            ],
        ),
        migrations.CreateModel(
            name='SequencingRunPoolItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna_conc', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lims.ExperimentalResult')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.SequencingRunPool')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=32)),
                ('type', models.IntegerField(choices=[(0, 'Fridge'), (1, 'Freezer')])),
                ('container_label', models.CharField(max_length=64)),
                ('shelf', models.CharField(blank=True, max_length=32, null=True)),
                ('box', models.CharField(blank=True, max_length=64, null=True)),
                ('sample_label', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='phagednaprep',
            name='storage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Storage'),
        ),
        migrations.AddField(
            model_name='phage',
            name='phagednaprep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.PhageDNAPrep'),
        ),
        migrations.AddField(
            model_name='phage',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.Organisation'),
        ),
        migrations.AddField(
            model_name='lysate',
            name='storage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Storage'),
        ),
        migrations.AddField(
            model_name='environmentalsamplecollection',
            name='env_sample',
            field=models.ManyToManyField(blank=True, through='lims.EnvironmentalSampleRelation', to='lims.EnvironmentalSample'),
        ),
        migrations.AddField(
            model_name='environmentalsamplecollection',
            name='storage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Storage'),
        ),
        migrations.AddField(
            model_name='environmentalsample',
            name='sample_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.SampleType'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='phage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Phage'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='sequencing_run_pool_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.SequencingRunPoolItem'),
        ),
        migrations.AlterUniqueTogether(
            name='sequencingrunpool',
            unique_together=set([('pool', 'run')]),
        ),
    ]
