# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-17 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalsample',
            name='sample_type',
            field=models.CharField(max_length=32),
        ),
        migrations.DeleteModel(
            name='SampleType',
        ),
    ]
