# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phage',
            old_name='host_lims',
            new_name='host',
        ),
    ]
