# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phage',
            name='primary_name',
            field=models.CharField(max_length=64),
        ),
    ]
