# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-16 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalsamplecollection',
            name='storage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Storage'),
        ),
        migrations.AlterField(
            model_name='lysate',
            name='storage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Storage'),
        ),
        migrations.AlterField(
            model_name='phagednaprep',
            name='storage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Storage'),
        ),
    ]
