# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phage',
            name='host_lims',
            field=models.ManyToManyField(blank=True, to='lims.Bacteria'),
        ),
    ]
