# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_auto_20161027_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phage',
            name='historical_names',
            field=models.TextField(blank=True),
        ),
    ]
