# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_auto_20161217_0120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bacteria',
            options={},
        ),
        migrations.AlterField(
            model_name='lysate',
            name='isolation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
