# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_auto_20161208_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lysate',
            name='phage',
        ),
        migrations.RemoveField(
            model_name='phagednaprep',
            name='lysate',
        ),
        migrations.RemoveField(
            model_name='phagednaprep',
            name='phage',
        ),
        migrations.AddField(
            model_name='phage',
            name='lysate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Lysate'),
        ),
        migrations.AddField(
            model_name='phage',
            name='phagednaprep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.PhageDNAPrep'),
        ),
    ]
