# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0004_auto_20161028_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phage',
            name='env_sample_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.EnvironmentalSampleCollection'),
        ),
    ]
