# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0004_remove_sequencingrunpoolitem_dna_conc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequencingrunpoolitem',
            old_name='experiments',
            new_name='dna_conc',
        ),
    ]
