# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0005_sequencingrunpoolitem_dna_prep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phagednaprep',
            name='morphology',
        ),
        migrations.AddField(
            model_name='phage',
            name='morphology',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Podophage'), (2, 'Myophage'), (3, 'Siphophage')], default=0),
        ),
    ]
