# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0005_auto_20161028_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phage',
            name='historical_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phage',
            name='host_lims',
            field=models.ManyToManyField(blank=True, null=True, to='lims.Bacteria'),
        ),
    ]
