# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0006_auto_20161222_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='phagednaprep',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
