# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0007_phagednaprep_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='phage',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
