# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0008_phage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chado_id', models.IntegerField(blank=True)),
                ('apollo_id', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genomea_id', models.CharField(max_length=32)),
                ('doi', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='assembly',
            name='sequence_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='phage',
            name='ncbi_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='phages',
            field=models.ManyToManyField(to='lims.Phage'),
        ),
        migrations.AddField(
            model_name='annotationrecord',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.Assembly'),
        ),
        migrations.AddField(
            model_name='annotationrecord',
            name='phage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.Phage'),
        ),
    ]
