# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0009_auto_20161223_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phage',
            name='ncbi_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sequencingrunpoolitem',
            name='pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.SequencingRunPool'),
        ),
    ]
