# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0014_auto_20161223_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingrunpoolitem',
            name='dna_prep',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.PhageDNAPrep'),
        ),
    ]
