# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0016_auto_20161223_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingrun',
            name='bioanalyzer_qc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='galaxy_history',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='methods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Experiment'),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='run_prep_spreadsheet',
            field=models.URLField(blank=True),
        ),
    ]
