# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0017_auto_20161223_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequencingrun',
            name='galaxy_history',
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='galaxy_library',
            field=models.URLField(blank=True, help_text='Galaxy Library URL'),
        ),
    ]
