# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0018_auto_20161223_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingrun',
            name='finalized',
            field=models.BooleanField(default=False, help_text='Once this is set, this model becomes read-only (except to people with access to django admin).'),
        ),
    ]
