# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 16:20
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0019_sequencingrun_finalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalsample',
            name='collection',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalsample',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalsample',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='environmentalsample',
            name='sample_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
