# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20161221_1908'),
        ('lims', '0023_auto_20170111_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequencingrun',
            old_name='methods',
            new_name='method',
        ),
        migrations.RemoveField(
            model_name='annotationrecord',
            name='phage',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='phage',
        ),
        migrations.RemoveField(
            model_name='phagednaprep',
            name='experiments',
        ),
        migrations.AddField(
            model_name='annotationrecord',
            name='annotator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
        migrations.AddField(
            model_name='annotationrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotationrecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='contig_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='contig_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='phage',
            name='can_be_annotated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phagednaprep',
            name='pfge',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='lims.ExperimentalResult'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Unpublished'), (2, 'Manuscript in preparation'), (3, 'In press'), (4, 'Published')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assembly',
            name='galaxy_dataset',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experimentalresult',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experimentalresult',
            name='run_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
