# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0024_auto_20170112_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='phage',
            name='morphology_qualifier',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Prolate'), (2, 'Isometric')], default=0),
        ),
        migrations.AddField(
            model_name='phage',
            name='needs_resequencing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='sequence_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='methods',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
