# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0026_auto_20170113_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phagednaprep',
            name='pfge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.ExperimentalResult'),
        ),
    ]
