# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0027_auto_20170113_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingrun',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
