# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0028_auto_20170113_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationrecord',
            name='apollo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotationrecord',
            name='chado_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotationrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
