# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0030_auto_20170113_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingrunpool',
            name='pool',
            field=models.CharField(max_length=64),
        ),
    ]
