# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0031_auto_20170117_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingrunpoolitem',
            name='dna_prep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.PhageDNAPrep'),
        ),
    ]
