# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='theme',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
