# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        ('account', '0002_fix_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='emails',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='initials',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='netid',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='account',
            name='nickname',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='orcid',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='account',
            name='orgs',
            field=models.ManyToManyField(blank=True, to='directory.Organisation'),
        ),
        migrations.AddField(
            model_name='account',
            name='original_id',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='account',
            name='tags',
            field=models.ManyToManyField(blank=True, to='directory.PersonTag'),
        ),
        migrations.AddField(
            model_name='account',
            name='theme',
            field=models.CharField(choices=[(b'default', b'Default'), (b'amelia', b'Amelia'), (b'cerulean', b'Cerulean'), (b'cosmo', b'Cosmo'), (b'cyborg', b'Cyborg'), (b'flatly', b'Flatly'), (b'journal', b'Journal'), (b'readable', b'Readable'), (b'simplex', b'Simplex'), (b'slate', b'Slate'), (b'spacelab', b'SpaceLab'), (b'united', b'United'), (b'superhero', b'Superhero'), (b'lumen', b'Lumen')], default='default', max_length=255),
        ),
    ]
