sudo: required

language: python
python: 2.7

services:
  - docker

before_install:
    - docker pull mdillon/postgis
    - sudo apt-get install -y jq

install:
    - pip install -r requirements.txt

script: bash .travis.sh
