sudo: required

language: python
python: 2.7

services:
  - docker

before_install:
    - docker pull mdillon/postgis

install:
    - pip install -r requirements.txt
    - make pg_launch
    - docker ps
