sudo: required

language: python
python: 2.7

services:
  - docker

before_install:
    - docker pull mdillon/postgis
    - sudo apt-get install -y jq chromium-chromedriver

install:
    - pip install -r requirements.txt
    - bash .travis.sh

script:
    - flake8 --statistics || true
    - python manage.py test
