# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editingrolegroup',
            name='role',
            field=models.IntegerField(choices=[(0, 'Viewer'), (1, 'Editor'), (2, 'Administrator')], default=0),
        ),
        migrations.AlterField(
            model_name='editingroleuser',
            name='role',
            field=models.IntegerField(choices=[(0, 'Viewer'), (1, 'Editor'), (2, 'Administrator')], default=0),
        ),
    ]
