# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-21 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bioproject',
            old_name='sample',
            new_name='sample_phage',
        ),
    ]
