# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-05 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_auto_20161005_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditingRoleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'Viewer'), (1, 'Editor'), (2, 'Administrator')])),
                ('bioproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Bioproject')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='EditingRoleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'Viewer'), (1, 'Editor'), (2, 'Administrator')])),
                ('bioproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Bioproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bioproject',
            name='access_group',
            field=models.ManyToManyField(blank=True, through='project.EditingRoleGroup', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='bioproject',
            name='access_user',
            field=models.ManyToManyField(blank=True, through='project.EditingRoleUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
