# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacteria',
            name='species',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='bacteria',
            name='strain',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='lysate',
            name='host_lims',
            field=models.ManyToManyField(blank=True, to='web.Bacteria'),
        ),
        migrations.AlterField(
            model_name='lysate',
            name='isolation',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='lysate',
            name='oldid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='lysate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.Person'),
        ),
        migrations.AlterField(
            model_name='lysate',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.Organisation'),
        ),
    ]
