# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assembly',
            options={'verbose_name_plural': 'assemblies'},
        ),
        migrations.AlterModelOptions(
            name='bacteria',
            options={'verbose_name_plural': 'bacteria'},
        ),
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name_plural': 'boxes'},
        ),
    ]
