# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='dna_prep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.PhageDNAPrep'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='sequencing_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.SequencingRunPool'),
        ),
        migrations.AlterField(
            model_name='lysate',
            name='env_sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.EnvironmentalSample'),
        ),
        migrations.AlterField(
            model_name='phagednaprep',
            name='lysate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Lysate'),
        ),
    ]
