# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 02:21
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalsample',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(help_text='The name which is written on the outside of the box.', max_length=64),
        ),
    ]
