# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160421_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='phagednaprep',
            name='lysate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Lysate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phagednaprep',
            name='experiments',
            field=models.ManyToManyField(blank=True, to='web.ExperimentalResult'),
        ),
        migrations.AlterField(
            model_name='phagednaprep',
            name='pfge_expected_size',
            field=models.FloatField(blank=True),
        ),
    ]
