# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20160427_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequencingRunPoolItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna_conc', models.FloatField(help_text='ng/\xb5L')),
                ('phage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.PhageDNAPrep')),
            ],
        ),
        migrations.RemoveField(
            model_name='sequencingrunpool',
            name='dna_preps',
        ),
        migrations.AddField(
            model_name='sequencingrunpoolitem',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SequencingRunPool'),
        ),
    ]
