# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160429_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequencingrun',
            name='pools',
        ),
        migrations.AddField(
            model_name='sequencingrunpool',
            name='run',
            field=models.ForeignKey(default='dab83e36-c1e4-48b3-8a7b-4257ba37b835', on_delete=django.db.models.deletion.CASCADE, to='web.SequencingRun'),
            preserve_default=False,
        ),
    ]
