# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20160817_2103'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sequencingrunpool',
            unique_together=set([('pool', 'run')]),
        ),
    ]
