# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20160817_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
