# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20160819_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentalsample',
            name='name',
        ),
    ]
