# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chado_id', models.IntegerField(blank=True, null=True)),
                ('apollo_id', models.TextField(blank=True)),
                ('phage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.Phage')),
            ],
        ),
    ]
