# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-05 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import fontawesome.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=32)),
                ('hidden', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
                ('icon', fontawesome.fields.IconField(blank=True, max_length=60)),
                ('priority', models.IntegerField(default=100)),
            ],
        ),
    ]
