# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0004_auto_20160429_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bioproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.EnvironmentalSample')),
            ],
        ),
    ]
