# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160429_0202'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioproject',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='bioproject',
            name='sample',
        ),
        migrations.AddField(
            model_name='bioproject',
            name='sample',
            field=models.ManyToManyField(to='web.EnvironmentalSample'),
        ),
    ]
