# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('emails', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=16)),
                ('fax_number', models.CharField(blank=True, max_length=16)),
                ('street_address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
