# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('emails', models.TextField()),
                ('phone_number', models.CharField(max_length=16)),
                ('fax_number', models.CharField(max_length=16)),
                ('street_address', models.TextField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('initials', models.TextField()),
                ('netid', models.CharField(max_length=32)),
                ('emails', models.TextField()),
                ('phone_number', models.CharField(max_length=16)),
                ('orcid', models.CharField(max_length=32)),
                ('orgs', models.ManyToManyField(to='directory.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='PersonTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(to='directory.PersonTag'),
        ),
    ]
