# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('emails', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=16)),
                ('fax_number', models.CharField(blank=True, max_length=16)),
                ('street_address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('default', 'Default'), ('primary', 'PI'), ('info', 'BICH464')], default='default', max_length=12)),
            ],
        ),
    ]
