# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_tags'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persontag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='persontag',
            name='parent',
        ),
        migrations.DeleteModel(
            name='PersonTag',
        ),
    ]
