# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_person_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='original_id',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
