# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_person_original_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
        migrations.AlterField(
            model_name='organisation',
            name='emails',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='fax_number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='street_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='emails',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='netid',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='orcid',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='person',
            name='orgs',
            field=models.ManyToManyField(blank=True, to='directory.Organisation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='original_id',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(blank=True, to='directory.PersonTag'),
        ),
    ]
